### ISSUE TITLE
[Feature Request] Support for Image Tokens

### ISSUE THREAD

**Issue by Veldkornet** [appzer/Athom-Homey-Pushsafer#1]
Could you please add support for the [Homey Image tokens](https://apps.developer.athom.com/tutorial-Flow-Tokens-Image.html) so that we can send images with apps like [Image Grabber](https://github.com/jordenc/image.grabber)?

I guess you may need to update to SDKv2 at the same time.

**Comment by appzer** [comment]
@Veldkornet can i invite you to test the new plugin when its ready

**Comment by Veldkornet** [comment]
Sure :)

**Comment by appzer** [comment]
@Veldkornet 

I updated the homey Pushsafer plugin.
Now with Image Support and all other Pushsafer Parameters.

It is possible that you can test the plugin?

Here the download link: [https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1](https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1)

Thanks Kevin

**Comment by Veldkornet** [comment]
```
Error in `app.json`:
SyntaxError: Unexpected token { in JSON at position 4263
```

I’m installing it now via CLI. Is it not maybe an option to push it to the store as a beta? Or is that the next step?

**Comment by Veldkornet** [comment]
Okay, fixed the app.json. By throwing away some brackets.
Although, I've probably broken something now with regard to how the labels are shown. So that's not the answer (see screenshots below)
Next error is when trying to run the app:

`Stack trace: /app.js:169 Homey.log("Pushsafer - No account configured yet"); ^ TypeError: Homey.log is not a function at buildPushsaferArray (/app.js:169:9) at MyApp.onInit (/app.js:19:3) at fs.stat.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/SDK.js:1:3280) at FSReqWrap.oncomplete (fs.js:153:5) Exit code: 1 Exit signal: null`

Okay, fixed that error too by changing Homey.log to console.log.
Not sure if that's what you wanted. 

Now the app installs and runs okay, but I see some visual issues in the settings:
![image](https://user-images.githubusercontent.com/10297361/37766218-90512994-2dc6-11e8-937c-af5f01e1514b.png)

This is probably me breaking things:
![image](https://user-images.githubusercontent.com/10297361/37766450-414a802e-2dc7-11e8-8a42-5b2d9f454805.png)
![image](https://user-images.githubusercontent.com/10297361/37766469-4f80f0e2-2dc7-11e8-9a27-7f15e5804e95.png)

Regardless, I added an image token, but it never arrived.

I'll just wait for you to fix everything up instead of me hacking things away ;)

**Comment by appzer** [comment]
@Veldkornet 

its quiet hard to test the scripts without hardware.
Here a fixed version.

Can you see the console.log in homey?
On line 71 of app.js i added a log entry where the image buffer should be outputed.

Can you send me the log after send a message with and without image.

[https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1](https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1)

Kevin

**Comment by appzer** [comment]
@Veldkornet 

can you add data to the pushsafer parameter fields?
Can you send me some screenshots, when the fields are selected!

![zwischenablage01](https://user-images.githubusercontent.com/3443312/37779797-8821a13c-2ded-11e8-9986-50ac138d6912.jpg)

**Comment by Veldkornet** [comment]
Okay, no install issues, so that's good. So I filled in all of the fields, with difficulty :) It's not your fault though, those cards are not useful, too small. Luckily, I also have access to the Beta App on iOS, where I can see all of the fields on separate lines :P 

![image](https://user-images.githubusercontent.com/10297361/37781894-f433dd96-2df1-11e8-9a7d-06d38db36b0d.png)

I receive the message, no image.

This is the console log:

─────────────── Logging stdout & stderr ───────────────
Pushsafer - Account configured successful
Log Not created. Error: already_exists
<Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 00 00 01 00 01 00 00 ff db 00 43 00 10 0b 0c 0e 0c 0a 10 0e 0d 0e 12 11 10 13 18 28 1a 18 16 16 18 31 23 25 1d ... >
{"status":1,"success":"message transmitted","available":24}

**Comment by appzer** [comment]
@Veldkornet 

OK, do all pushsafer parameters (icon, sound...) specified in Homey match the received push message?

Please try [https://apps.athom.com/app/image.grabber](https://apps.athom.com/app/image.grabber) to grab an image and use the token in the pushsafer app!

kevin

**Comment by Veldkornet** [comment]
Yes, that's what I did. Everything looks good, except that I don't get the image :(
Also, I saw that all of the fields are mandatory, if that's the intention.

Icon = Correct
Colour = Correct
Title = Correct 
Message = Correct
Link = Correct
Link Name = Correct
Sound = Correct
Vibration = Correct
Time To Live = Correct

**Comment by Veldkornet** [comment]
If it helps, the telegram app send the Image tokens correctly:

https://github.com/jordenc/org.telegram.api.bot


One other minor item, in the settings, there’s no visual verification that your key was saved correctly after you push the save button. So I wasn’t sure if the button worked. I’d expect a green tick to appear or something. 

Also, assuming there’s nothing that can be done with the visual display of the cards until Homey gets updated to 2.0.  In which case I suggest that you put an info page in the settings which pretty much says:
Filed 1 = Title
Field 2 = Message 
Etc. 

Then maybe a link to your API page that has all the different parameters.

**Comment by appzer** [comment]
@Veldkornet 

So now it should work with image.grabber token
Please download the latest changes: [https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1](https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1)

In the homey api reference i do not find anything about field mandatory!
[https://developer.athom.com/docs/apps/tutorial-Flow-Arguments.html](https://developer.athom.com/docs/apps/tutorial-Flow-Arguments.html)

Kevin

**Comment by appzer** [comment]
@Veldkornet 

if you need some api calls for testing, please send me your pushsafer username

**Comment by Veldkornet** [comment]
Ooh thanks, that would be useful. My username there is also Veldkornet. 

I guess if the fields are shown, they are mandatory :P

I’ll test it in a bit.

**Comment by appzer** [comment]
@Veldkornet 
i increased your api call.
Hope your tests are successful

**Comment by Veldkornet** [comment]
Problem,

I have nowhere to put the image tag, it disappeared. 

![image](https://user-images.githubusercontent.com/10297361/37799062-e42c8880-2e1e-11e8-9881-98ca3b8fdbb4.png)

I see what happened, it became a field to fill in instead of the place where you put the tag. 

I like the colour selector though! works great on the iOS app.

**Comment by appzer** [comment]
The first one: Afbeelding token / image token

**Comment by appzer** [comment]
@Veldkornet 

when you select a field do you see a field description?

**Comment by Veldkornet** [comment]
I see, usually that’s not a problem, but for some reason its not letting me add the token there. 
i think it was better when it had a seperace section, like you had it here:

![image](https://user-images.githubusercontent.com/10297361/37799718-db05c7d8-2e20-11e8-8fab-023d884dfc4b.png)

**Comment by Veldkornet** [comment]
I don’t see the fields on the web interface. What you see in the screenshot is literally how it is. 

From the beta iOS app it’s fine though 

![e4af2984-f031-4f09-a8d4-44bb2b78c73e](https://user-images.githubusercontent.com/10297361/37799897-69a0b584-2e21-11e8-93ce-2281c8611c1f.png)

**Comment by appzer** [comment]
@Veldkornet 

can you add the token here? 

![zwischenablage01](https://user-images.githubusercontent.com/3443312/37799847-3fafb9aa-2e21-11e8-9929-1facaa38b084.jpg)

**Comment by appzer** [comment]
i found the solution here [https://github.com/PandaNL/nl.tonversteeg.pushbullet](https://github.com/PandaNL/nl.tonversteeg.pushbullet)

**Comment by Veldkornet** [comment]
No, I can drag any other token into that box, but not the image token. 

I can only add the image token to that image token field like you had it in the previous build.

**Comment by Veldkornet** [comment]
Do you mean that you got the code for the image token from the Pushbullet app? Because it doesn’t work there either :P

I only know that the telegram app works correctly with the image token, as I use it almost daily:

https://github.com/jordenc/org.telegram.api.bot

The email sender should also be okay:

https://github.com/jordenc/email-sender

**Comment by appzer** [comment]
@Veldkornet 
Please try again, i modified it to the old version with image droptoken > use image grabber

[https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1](https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1)

**Comment by Veldkornet** [comment]
Great! I can use the tag again!
![image](https://user-images.githubusercontent.com/10297361/37822025-9cfe0f8a-2e85-11e8-8a89-a5ca6a458950.png)

Still all of the parameters look correct and the message arrives...
However, still no image :(

**Comment by appzer** [comment]
@Veldkornet 
can you at this
`console.log('ImageData:'+image);`

before this
`if (typeof pMessage == 'undefined' || pMessage == null || pMessage == '') return new Error("Message can not be empty");
				return pushsaferSend(tempUser, pMessage, title, device, icon, iconcolor, sound, vibration, url, urltitle, time2live, image);`

And post what the log said

**Comment by Veldkornet** [comment]
─────────────── Logging stdout & stderr ───────────────
Pushsafer - Account configured successful
Log Not created. Error: already_exists
ImageData: [object Object]
{"status":1,"success":"message transmitted","available":1003}

**Comment by appzer** [comment]
@Veldkornet 
here a new try
[https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1](https://www.dropbox.com/s/7ee7zydvow6juio/Athom-Homey-Pushsafer.zip?dl=1)

Without ImageGrabber, enter the url of an image into the field Image URL (first one)
Take a look into the log > ImageData

I load the image and convert it to base64 string directly in the pushsafer app

**Comment by Veldkornet** [comment]
```
─────────────── Logging stdout & stderr ───────────────
module.js:540
    throw err;
    ^

Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/request/index.js:17:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)

--- INFO: de.appzer.pushsafer has been killed ---
```

**Comment by appzer** [comment]
please try again, forgot to add the required node modules

**Comment by Veldkornet** [comment]
It works! Very nice, very nice!

**Comment by appzer** [comment]
puuuuhhhh thats great can you also test images from an secure server like this one
https://www.pushsafer.com/de/assets/logos/logo.png

**Comment by appzer** [comment]
do you also have an ip camera to send images from with user credentials like http://[user]:[password]@192.168.1.110:8001/snapshot.cgi

**Comment by Veldkornet** [comment]
Right, so connecting to my Foscam IP camera via HTTPS gives a problem because it's a self signed certificate. I guess you will need to add the equivelant of cURL's "-k" command.

```
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```
Connecting via HTTP works fine, which indeed uses a URL like: 
http://192.168.1.110:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=[USERNAME]&pwd=[PASSWORD]

Also, the image from your site works okay: https://www.pushsafer.com/de/assets/logos/logo.png

It's also a lot quicker than when using Image Grabber. At least now I will be able to see who rang the door bell before the person leaves ;)

**Comment by Veldkornet** [comment]
The only other items I can think of are things that probably aren't in your control, but rather a limitation of Homey's interface until it gets it's 2.0 update.
1. The config card, you can't see what's going on. As mentioned, I have access to the Beta iOS app so this is not a problem for me, but I don't think that everyone has access to this.
2. All the fields are mandatory. Something like the URL I probably won't need for my doorbell.

Considering the two items above, it may be an idea to submit the app to the store as a beta. That way, the current stable users are then not affected but people do have the option to use the new beta version. Until Homey get's it's update anyway.

Anyway, that's just my opinion.

**Comment by appzer** [comment]
can you change this line

`let request = require('request').defaults({ encoding: null });`

to this one

`let request = require('request').defaults({ "strictSSL": false, "encoding": null });`

And try again to send an image from https

I wrote athom support an mail to solve the mandatory issue

**Comment by Veldkornet** [comment]
Confirmed, https to my IP cam working too.

**Comment by appzer** [comment]
great i will upload the plugin to athom, hope to get a quick answer from the support

**Comment by appzer** [comment]
@Veldkornet  hi again

can you try to install the app from github

[https://github.com/appzer/Athom-Homey-Pushsafer](https://github.com/appzer/Athom-Homey-Pushsafer)

After that i will publish it on athom

Thanks Kevin

**Comment by Veldkornet** [comment]
Yup, still working! :)
