### ISSUE TITLE
[Feature Request] Custom Notifications

### ISSUE THREAD

**Issue by Veldkornet** [appzer/Athom-Homey-Pushsafer#2]
I noticed in Pushsafer that you can use different sounds and icons for the messages. Is it possible to bring some of this over to the app?

Ie, Pushsafer will send all the notifications from home, but if it's the doorbell, I'd prefer that I have a doorbell sound, vs the alarm where you could use an alarm sound....

![image](https://user-images.githubusercontent.com/10297361/37585736-69ca2406-2b5a-11e8-98ae-26abdb824f59.png)

**Comment by appzer** [comment]
I will integrate that with the next update!
Currently you can set up an alias email with predefined parameters

![zwischenablage01](https://user-images.githubusercontent.com/3443312/37586518-e25515dc-2b5c-11e8-844d-9749dbad404d.jpg)
