### ISSUE TITLE
App Icon Missing in some locations 

### ISSUE THREAD

**Issue by Veldkornet** [appzer/Athom-Homey-Pushsafer#3]
**Homey:** 1.5.8
**PushSafer:** 0.0.4

Not a major issue, but I only noticed now that the app icon is missing from a few locations, mostly in the new beta app. From the stable from the Homey app on the pc, the icon does show.

![f19425cf-ea2f-4e8a-8b7c-53dac78211ab](https://user-images.githubusercontent.com/10297361/37872700-cdb7d294-300d-11e8-967b-d8c8638e03e4.jpeg)

**Comment by appzer** [comment]
i uploaded a new version with a fixed svg icon, hope that will solve the issue

**Comment by Veldkornet** [comment]
FYI, I just received the update. 

Note that it did not resolve the issue. 

On the web view for example, it’s shown correctly. It’s only in the new beta app that it’s not showing anywhere. 

Unclear what makes it different from all the other apps which do work. Although functionally, everything works okay.

**Comment by appzer** [comment]
i dont know where the issue is.
The athom support has not answered yet

**Comment by Veldkornet** [comment]
I think you should just buy a Homey! 
You’ll love using it anyway! 😉

**Comment by appzer** [comment]
😉
