### ISSUE TITLE
Flow card for Pushsafer "cropped" in Homey

### ISSUE THREAD

**Issue by JohanMarini** [appzer/Athom-Homey-Pushsafer#4]
Homey 1.5.8
Pushsafer 0.0.4

Hello!
When trying to use a Pushsafer Flow Card in Homey, all the property fields/controls are cropped.
I have restarted Pushsafer app and also rebooted Homey.
![ps flow card1](https://user-images.githubusercontent.com/37127032/37874453-c667798c-302f-11e8-89a9-e44878347773.PNG)
![ps flow card2](https://user-images.githubusercontent.com/37127032/37874454-c6849da0-302f-11e8-9563-b8b6296eece0.PNG)

Please see attached images.
Kindest Regards
Johan

**Comment by appzer** [comment]
i know...this happens because there are so many fields in the flow.
I have already contacted the Athom Support, I hope there is a solution to properly format the flow.

But you can enter all the data to send the push notification correctly with all parameters?

**Comment by Veldkornet** [comment]
@JohanMarini if you have the Android or iOS beta app, use that instead. 

Otherwise, I can give you the order of the attributes, and you can just push the “tab” key to scroll through them and enter all the fields.

**Comment by JohanMarini** [comment]
Thanks for your quick return!
Yes, please list the order of the attributes - I guess it would be enough for now.
Kindest Regards.

**Comment by Veldkornet** [comment]
- **Pushsafer Notification**
_1. Message_
_2. Title_
_3. Device or Device Group ID_
_4. Icon ID (1-176)_
_5. Colour (Tab skips over this property, use the colour wheel afterwards)_
_6. Sound ID (0-50)_
_7. Vibration (0-3)_
_8. URL_
_9. Title of URL_
_10. Time To Live (0-43200)_


- **Pushsafer Image**
_1. URL of Image_
_2. Message_
_3. Title_
_4. Device or Device Group ID_
_5. Icon ID (1-176)_
_6. Colour (Tab skips over this property, use the colour wheel afterwards)_
_7. Sound ID (0-50)_
_8. Vibration (0-3)_
_9. URL_
_10. Title of URL_
_11. Time To Live (0-43200)_

**Comment by JohanMarini** [comment]
Thanks! I guess that some of them may be ok to leave "null"?

**Comment by Veldkornet** [comment]
From a PushSafer side, yes. I’m just not sure if Homey lets you do that, I think it assumes all fields mandatory at this stage, might be a (v2) feature :P 

For some things like URL, I just put “athomhomey://“ with the URL text “Open Homey”, which will then open the Homey app (on iOS anyway).

**Comment by appzer** [comment]
thanks guys, i added this info to the documentation.

**Comment by JohanMarini** [comment]
Hmm... I get problem with:
Device: I try to enter "All" or my device name or my device ID, but doesn't accept
URL: I try to leave "null" or enter "None"
Title of URL: I try to leave "null" or enter "None"
Time To Live: I try to enter "60" for example (seconds?)
Please advice :-)

**Comment by appzer** [comment]
for all devices leave empty or enter only "a"
For a single device the id (integer number) you will find this in your pushsafer.com dashboard.

All fields are mandatory, i can not change this currently.
So enter http://www.google.de or a URL you like.

Time to Live = 0 do not delete automatically or a number from 1- 43200 (seconds)

Take a look at the pushsafer.com API > **[https://www.pushsafer.com/en/pushapi]()**

**Comment by heronimus68** [comment]
trying to configure an Pushsafer action in a flow via the Android APP, but it doesn't let me save the settings.

**Comment by appzer** [comment]
@heronimus68 can you provide a screenshot

**Comment by heronimus68** [comment]
![screenshot](https://user-images.githubusercontent.com/46626324/51087020-15138700-174e-11e9-951a-f8ee4d7e822d.jpg)
The save button is in the upperright corner,

**Comment by heronimus68** [comment]
> 
> 
> @heronimus68 can you provide a screenshot

I'm sorry, now i read that all fields are mandatory. After filing in all fields, the save button is enabled.

**Comment by appzer** [comment]
no problem...
